---
# playbook.yml
- name: "Provision New Servers"
  hosts: localhost
  become: true
  vars:
    - ansible_become_password: 'setupuser'

  tasks:
  - name: Install Apache
    package:
      name: "apache2"
      state: present

  - name: Install vsftp
    package:
      name: "vsftpd"
      state: present
