# Release a snapshot base image to DigitalOcean
name: digitalocean

# Only run when a release is pushed
on:
  push:
    tags: release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Get the short sha
      id: git_short_sha
      run: echo ::set-output name=OUTPUT::$(echo $GITHUB_SHA | cut -c -7)

    - name: Get the tag
      id: git_tag
      run: echo ::set-output name=OUTPUT::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: What checkout are we on?
      run: echo "$BUILD_VERSION"
      env:
        BUILD_VERSION: ${{ steps.git_short_sha.outputs.OUTPUT }}

    - name: Build the server on DigitalOcean
      uses: riznob/packer-build-action@v1.1
      with:
        templateFile: './packer/digitalocean.json'
        varFile: './vars/digitalocean.json'
      env:
        DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
