# Release a snapshot base image to DigitalOcean
name: digitalocean

# Only run when a release is pushed
on:
  push:
    tags: release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Build the server on DigitalOcean
      uses: riznob/packer-build-action@v1.1
      with:
        templateFile: './packer/digitalocean.json'
        varFile: './vars/digitalocean.json'
      env:
        BUILD_VERSION: ${GITHUB_SHA::8}
        IMAGE_NAME: "homework-webserver"
        DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
